import nome
import sys

erroInicializar = False


atividade = nome.inicializar()

if len(atividade) != 3:
	erroInicializar = True
else:
	for linha in atividade:
		if len(linha) != 3:
			erroInicializar = True
		else:
			for elemento in linha:
				if elemento != '.':
					erroInicializar = True
if erroInicializar:
	sys.exit(1)
else:
	sys.exit(0)

